---
- name: Disallow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart ssh

- name: Disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: Restart ssh

- name: Enable OpenSSH on ufw
  become: yes
  command: ufw allow OpenSSH
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Enable ORPort on ufw
  become: yes
  command: ufw allow 9000/tcp
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
